### ISSUE TITLE
Chore: Add changelog/maintain releases

### ISSUE THREAD

**Issue by escapedcat** [aaronbarnardsound/lnmessage#16]
Adding a changelog and maintaining Github releases helps people to see what's new and what might break (i.e. with a major release).

Tools like https://github.com/googleapis/release-please and [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0) can help with this or even the Github releases, i.e.:
![image](https://user-images.githubusercontent.com/1016218/216821743-714adbe0-ee6d-434d-ab2b-c46039278c13.png)

This can also help people using dep-update tools like depfu.com. Currently we get:
![image](https://user-images.githubusercontent.com/1016218/216821811-43e41fc3-23bf-463e-8d1b-3e86b2a482af.png)

https://github.com/getAlby/lightning-browser-extension/pull/2070

This is just a nit really. Happy to help with this if wanted.

**Comment by lnbc1QWFyb24** [comment]
Yeah good call. I have been meaning to be less of a cowboy with this repo now that other projects are using it. Thanks for the nudge, I will get proper branches, releases and CI publishing setup asap!

**Comment by lnbc1QWFyb24** [comment]
Hey @escapedcat I just released [v0.1.0](https://github.com/aaronbarnardsound/lnmessage/releases/tag/0.1.0) with a better release and tagging process. Let me know if there is enough info in the release notes etc. I opted for doing it manually as that is the process I am familiar with, but open to trying out some of those tools you mentioned if the manual process is not adequate.

**Comment by escapedcat** [comment]
All good. Let's see how the next depfu updates will look like.

**Comment by escapedcat** [comment]
Quote depfu.com:

> Ok, so this case we didn't find the Github repo since there is no repository field in the package.json. I've fixed it manually now, so it should start working for the next PRs as the tags etc look correct.

Could you add the repo info to the package.json to help services to get the needed release info?:
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository

**Comment by lnbc1QWFyb24** [comment]
@escapedcat Oh yep I can definitely do that.

**Comment by lnbc1QWFyb24** [comment]
Fixed in [v0.2.0](https://github.com/aaronbarnardsound/lnmessage/releases/tag/0.2.0)
