### ISSUE TITLE
Replace secp256k1 with @noble/secp256k1

### ISSUE THREAD

**Issue by im-adithya** [aaronbarnardsound/lnmessage#21]
Thanks for building this :heart:

Was thinking if we could replace the [secp256k1](https://www.npmjs.com/package/secp256k1) package with [@noble/secp256k1](https://www.npmjs.com/package/@noble/secp256k1), which claims to be faster and is very light.

It also has all the methods currently being used except for `publicKeyVerify`
```
ecdh             -> getSharedSecret
publicKeyCreate  -> getPublicKey
privateKeyVerify -> utils.isValidPrivateKey
publicKeyVerify  -> :/

**Comment by lnbc1QWFyb24** [comment]
Hey @im-adithya yeah I believe this would be possible and might be worth doing. Feel free to open a PR that does this and I can review, otherwise I can try and get to this at some point.

**Comment by lnbc1QWFyb24** [comment]
Completed in [v0.2.0](https://github.com/aaronbarnardsound/lnmessage/releases/tag/0.2.0). Thanks @im-adithya for the PR!
