### ISSUE TITLE
Possibility for events and hooks

### ISSUE THREAD

**Issue by niteshbalusu11** [aaronbarnardsound/lnmessage#31]
I am not sure if this is possible but wanted to check. Is there a possibility for streaming events and working with hooks via commando-runes, if yes, can it be built into lnmessage?

**Comment by lnbc1QWFyb24** [comment]
Commando allows for calling any RPC methods that are available on the node. I don't think (AFAK) there are RPC methods that are built in by default that give you access to streaming events and working with hooks.

You could create a plugin that exposes RPC methods that give access to the events and hooks and then use Commando to call those methods, but users would obviously need that plugin installed for that to work.

I would also love to be able to just hook in to events, so maybe that is something we could ask the CoreLN team if they would be interested in implementing a default plugin that exposes the events and hooks?

**Comment by niteshbalusu11** [comment]
Yeah absolutely, It's a little annoying to me that you have to build two different things with JSON-RPC and plugins to get access to everything.

**Comment by lnbc1QWFyb24** [comment]
Yeah agreed

**Comment by lnbc1QWFyb24** [comment]
This [new API](https://community.corelightning.org/c/developers/new-wait-pagination-api-proposal-feedback-please) that Rusty is working on might also be what you need?

**Comment by niteshbalusu11** [comment]
Interesting. Let me check out the PR. 

I didn't find a solution to what I want so I started building a plugin that starts a websocket server that gives you JSON-RPC, events and hooks all in one.
