### ISSUE TITLE
WebSockets URL formatting for proxied connections without a specified port is not possible

### ISSUE THREAD

**Issue by danieldaquino** [aaronbarnardsound/lnmessage#52]
## Summary

It seems that the LNMessage constructor does not support building proxied URLs without specifying port numbers, and when specifying port numbers, the resulting URL fails.

### Method A

1. Using a browser context (web app, e.g. React, Next.js), try to initiate a connection like so:

```javascript
const ln = new Lnmessage({
      remoteNodePublicKey: "<NODE_ID_HERE>",
      // The websocket proxy address of the node
      wsProxy: `wss://proxy.example.com`,
      ip: `ln.example.com`,
      wsProtocol: 'wss:',
    })
```

2. Try to connect and run lightning RPC commands. Use Chrome dev tools (or equivalent) to see console logs

### Method B

1. Using a browser context (web app, e.g. React, Next.js), try to initiate a connection like so:

```javascript
const ln = new Lnmessage({
      remoteNodePublicKey: "<NODE_ID_HERE>",
      // The websocket proxy address of the node
      wsProxy: `wss://proxy.example.com`,
      ip: `ln.example.com`,
      wsProtocol: 'wss:',
      port: 9735
    })
```

2. Try to connect and run lightning RPC commands. Use Chrome dev tools (or equivalent) to see console logs

### Method A

The final URL connection string should be `wss://proxy.example.com/ln.example.com`, and connection should work

### Method B

The final connection should work. (Unsure what the proper URL would be)

### Method A

Fails one of the constructor checks, claiming that `undefined` is not a valid port number

### Method B

1. The final URL connection string is `wss://proxy.example.com/ln.example.com:9735` (Unsure if that colon should be url encoded)
2. The connection itself fails

## Workaround

I added this line below the constructor to manually format the URL

```javascript
ln.wsUrl = `wss://proxy.example.com/ln.example.com`
```

This seems to work

**Comment by lnbc1QWFyb24** [comment]
Hey Daniel,

If you are looking to connect via a proxy, try leaving out the `wsProtocol` param which is used for direct WS connections to the node:

```javascript
const ln = new Lnmessage({
  remoteNodePublicKey: "<NODE_ID_HERE>",
  ip: `ln.example.com`,
  port: 9735,
  wsProxy: `wss://proxy.example.com`
})
```
